name: generatesci

on: push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout repo
       uses: actions/checkout@v4
    -  name: listing the files
       run: ls -ltra
    -  name: using the script to execute commands
       run: ./ascii-script.sh
